/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ejerciciotabla;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yesner
 */
public class frmClientes extends javax.swing.JInternalFrame {
   
  //variables global el modelo de la tabla
  DefaultTableModel modelTablaClientes;
  /**
   * Creates new form frmClientes
   */
  public frmClientes() {
    initComponents();
    confiTablaCliente();
  }
  
  public void confiTablaCliente(){
    
    modelTablaClientes = new DefaultTableModel();
    //nombre de la tabla de diseno
    TbCliente.setModel(modelTablaClientes);
    modelTablaClientes.addColumn("ID");
    modelTablaClientes.addColumn("Nombre");
    modelTablaClientes.addColumn("Apellido");
    modelTablaClientes.addColumn("Sexo");
    modelTablaClientes.addColumn("Telefono");
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    txtid = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    txtnombre = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    txtapellido = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    cbosexo = new javax.swing.JComboBox<>();
    jLabel5 = new javax.swing.JLabel();
    txttelefono = new javax.swing.JTextField();
    jPanel2 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    TbCliente = new javax.swing.JTable();
    jPanel3 = new javax.swing.JPanel();
    btnguardar = new javax.swing.JButton();
    btneliminar = new javax.swing.JButton();
    jPanel4 = new javax.swing.JPanel();
    exip = new javax.swing.JPanel();
    exil = new javax.swing.JLabel();

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos Del Cliente"));
    jPanel1.setLayout(new java.awt.GridLayout(5, 2));

    jLabel1.setText("ID");
    jPanel1.add(jLabel1);
    jPanel1.add(txtid);

    jLabel2.setText("Nombre");
    jPanel1.add(jLabel2);
    jPanel1.add(txtnombre);

    jLabel3.setText("Apellido");
    jPanel1.add(jLabel3);
    jPanel1.add(txtapellido);

    jLabel4.setText("Sexo");
    jPanel1.add(jLabel4);

    cbosexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino", "Prefiero no Decir", " " }));
    jPanel1.add(cbosexo);

    jLabel5.setText("Telefono");
    jPanel1.add(jLabel5);
    jPanel1.add(txttelefono);

    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Clientes Guardados"));

    TbCliente.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null, null},
        {null, null, null, null, null},
        {null, null, null, null, null},
        {null, null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
      }
    ));
    TbCliente.setGridColor(new java.awt.Color(0, 0, 0));
    jScrollPane1.setViewportView(TbCliente);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(89, 89, 89))
    );

    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Operaciones"));

    btnguardar.setText("Guardar");
    btnguardar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnguardarActionPerformed(evt);
      }
    });

    btneliminar.setText("Eliminar");
    btneliminar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btneliminarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addGap(60, 60, 60)
        .addComponent(btnguardar)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(btneliminar)
        .addContainerGap(540, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addGap(27, 27, 27)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnguardar)
          .addComponent(btneliminar))
        .addContainerGap(44, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 28, Short.MAX_VALUE)
    );

    exip.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        exipMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        exipMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        exipMouseExited(evt);
      }
    });

    exil.setText("X");

    javax.swing.GroupLayout exipLayout = new javax.swing.GroupLayout(exip);
    exip.setLayout(exipLayout);
    exipLayout.setHorizontalGroup(
      exipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exipLayout.createSequentialGroup()
        .addContainerGap(12, Short.MAX_VALUE)
        .addComponent(exil, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    exipLayout.setVerticalGroup(
      exipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(exipLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(exil)
        .addContainerGap(7, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addGap(3, 3, 3)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(6, 6, 6))
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(exip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(exip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(51, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
    eliminar();
  }//GEN-LAST:event_btneliminarActionPerformed

  private void exipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exipMouseClicked
    System.exit(0);
  }//GEN-LAST:event_exipMouseClicked

  private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
    llenarObjeto();
  }//GEN-LAST:event_btnguardarActionPerformed

  private void exipMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exipMouseEntered
        exip.setBackground(Color.red);
        exil.setForeground(Color.white);
  }//GEN-LAST:event_exipMouseEntered

  private void exipMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exipMouseExited
        exip.setBackground(Color.white);
        exil.setForeground(Color.black);
  }//GEN-LAST:event_exipMouseExited
  public void llenarObjeto(){
    Object[] oDatos = new Object[5];
    oDatos [0] = txtid.getText();
    oDatos [1] = txtnombre.getText();
    oDatos [2] = txtapellido.getText();
    oDatos [3] = cbosexo.getSelectedItem();
    oDatos [4] = txttelefono.getText();
    modelTablaClientes.addRow(oDatos);
    limpiar();
  
  
  }
  public void limpiar(){
    txtid.setText("");
    txtnombre.setText("");
    txtapellido.setText("");
    cbosexo.setSelectedIndex(-1);
    txttelefono.setText("");
  
  }
  
  public void eliminar(){
    int fila = TbCliente.getSelectedRow();
    if(fila != -1){
      modelTablaClientes.removeRow(fila);
    }else
    JOptionPane.showMessageDialog(null, "Debe seleccionar una fila");
  }
  
  

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTable TbCliente;
  private javax.swing.JButton btneliminar;
  private javax.swing.JButton btnguardar;
  private javax.swing.JComboBox<String> cbosexo;
  private javax.swing.JLabel exil;
  private javax.swing.JPanel exip;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextField txtapellido;
  private javax.swing.JTextField txtid;
  private javax.swing.JTextField txtnombre;
  private javax.swing.JTextField txttelefono;
  // End of variables declaration//GEN-END:variables
}
