
package trabajo.acumulativo;

import java.awt.Color;
import javax.swing.ButtonGroup;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;



/**
 *
 * @author yesner
 */
public class FrmCuestionario extends javax.swing.JInternalFrame {
  

  
   
  /**
   * Creates new form FrmCuestionario
   */
  public FrmCuestionario() {
    initComponents();
    Quitarselection();
  }
  
  void Quitarselection(){
       ButtonGroup btg1 = new ButtonGroup();
       btg1.add(rbtn58);
       btg1.add(rbtn34);
       btg1.add(rbtn31);
       btg1.add(rbtn40);
       
       ButtonGroup btg2 = new ButtonGroup();
       btg2.add(rbtnmarte);
       btg2.add(rbtnjupiter);
       btg2.add(rbtntierra);
       btg2.add(rbtnsaturno);
       
       ButtonGroup btg3 = new ButtonGroup();
       btg3.add(rbtnola);
       btg3.add(rbtndesicion);
       btg3.add(rbtnhay);
       btg3.add(rbtnahi);
  
  }

  void Validar1Pregunta(){
    
         if (rbtn31.isSelected()) {
               lbr1.setText("Cierto");
                 lbr1.setForeground(Color.blue);
       }else {
                   lbr1.setText("Error");
                        lbr1.setForeground(Color.red);
             }
     
     
     
     
 }
  
  void Validar2Pregunta(){
    
       if (rbtnjupiter.isSelected()) {
              lbr2.setText("Cierto");
                  lbr2.setForeground(Color.blue);
        }else {
                   lbr2.setText("Error");
                    lbr2.setForeground(Color.red);
          }
     
     
 }
  
  void Validar3Pregunta(){
    
       if (rbtndesicion.isSelected()) {
          lbr3.setText("Cierto");
           lbr3.setForeground(Color.blue);
        }else {
            lbr3.setText("Error");
             lbr3.setForeground(Color.red);
       }
}
  
  void Validar4Pregunta(){
     
        if (cboxlerdo.isSelected()) {
          lbr4.setText("Error");
          lbr4.setForeground(Color.red);
       }else if (cboxastuto.isSelected() || cboxlisto.isSelected() || cboxsagaz.isSelected()){
          lbr4.setText("Cierto");
          lbr4.setForeground(Color.blue);
       }
     
  
}
  
  public boolean noButtonSelected() {
    JRadioButton[] buttons={rbtn58,rbtn34,rbtn31,rbtn40,rbtnmarte,rbtnjupiter,rbtntierra,rbtnsaturno,rbtnola,rbtndesicion,rbtnhay,rbtnahi};
    for (JRadioButton button : buttons) {
        if (button.isSelected()) {
            return false;
        }
    }
    return true;
}
  
  public boolean nocheckSelected(){
    JCheckBox[] button = {cboxsagaz,cboxlisto,cboxlerdo,cboxastuto};
      for (JCheckBox jCheckBox : button) {
         if (jCheckBox.isSelected()) {
            return false;
        }
    }
        
    return true;
  }
                 
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    lbpg1 = new javax.swing.JLabel();
    rbtn58 = new javax.swing.JRadioButton();
    rbtn34 = new javax.swing.JRadioButton();
    rbtn31 = new javax.swing.JRadioButton();
    rbtn40 = new javax.swing.JRadioButton();
    lbr1 = new javax.swing.JLabel();
    lbpg2 = new javax.swing.JLabel();
    rbtnmarte = new javax.swing.JRadioButton();
    rbtnjupiter = new javax.swing.JRadioButton();
    rbtntierra = new javax.swing.JRadioButton();
    rbtnsaturno = new javax.swing.JRadioButton();
    lbr2 = new javax.swing.JLabel();
    lbpg3 = new javax.swing.JLabel();
    rbtnola = new javax.swing.JRadioButton();
    rbtndesicion = new javax.swing.JRadioButton();
    rbtnhay = new javax.swing.JRadioButton();
    rbtnahi = new javax.swing.JRadioButton();
    lbr3 = new javax.swing.JLabel();
    lbpg4 = new javax.swing.JLabel();
    cboxsagaz = new javax.swing.JCheckBox();
    cboxlisto = new javax.swing.JCheckBox();
    cboxlerdo = new javax.swing.JCheckBox();
    cboxastuto = new javax.swing.JCheckBox();
    lbr4 = new javax.swing.JLabel();
    btnmostrar = new javax.swing.JButton();

    setVisible(true);

    lbpg1.setText("4 * 6 + 3 + 2 * 2 =");

    rbtn58.setText("58");

    rbtn34.setText("34");

    rbtn31.setText("31");

    rbtn40.setText("40");

    lbr1.setBackground(new java.awt.Color(0, 0, 255));
    lbr1.setForeground(new java.awt.Color(204, 204, 204));

    lbpg2.setText("Nombre del quinto planeta:");

    rbtnmarte.setText("Marte");

    rbtnjupiter.setText("Jupiter");

    rbtntierra.setText("Tierra");

    rbtnsaturno.setText("Saturno");

    lbr2.setBackground(new java.awt.Color(0, 0, 255));
    lbr2.setForeground(new java.awt.Color(204, 204, 204));

    lbpg3.setText("Palabra con error ortográfico:");

    rbtnola.setText("ola");

    rbtndesicion.setText("desición");

    rbtnhay.setText("hay");

    rbtnahi.setText("ahí");

    lbr3.setBackground(new java.awt.Color(0, 0, 255));
    lbr3.setForeground(new java.awt.Color(204, 204, 204));

    lbpg4.setText("Sinónimos de inteligente:");

    cboxsagaz.setText("sagaz");

    cboxlisto.setText("listo");

    cboxlerdo.setText("lerdo");

    cboxastuto.setText("astuto");

    lbr4.setBackground(new java.awt.Color(0, 0, 255));
    lbr4.setForeground(new java.awt.Color(204, 204, 204));

    btnmostrar.setText("Mostrar");
    btnmostrar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnmostrarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(24, 24, 24)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(lbpg1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(lbpg2))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(rbtnmarte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnjupiter))
              .addGroup(layout.createSequentialGroup()
                .addComponent(rbtn58, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rbtn34))
              .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(rbtndesicion))))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(lbpg3)
              .addComponent(lbpg4))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(rbtnola)
              .addGroup(layout.createSequentialGroup()
                .addComponent(cboxsagaz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboxlisto))
              .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnmostrar)))))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(rbtntierra)
              .addComponent(rbtn31)
              .addComponent(rbtnhay))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(rbtnsaturno)
                  .addComponent(rbtn40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(lbr1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(lbr2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
              .addGroup(layout.createSequentialGroup()
                .addComponent(rbtnahi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbr3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
          .addGroup(layout.createSequentialGroup()
            .addComponent(cboxlerdo)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(cboxastuto)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(lbr4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(14, 14, 14)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(lbr1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rbtn58)
                .addComponent(rbtn34)
                .addComponent(rbtn31)
                .addComponent(rbtn40))))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lbpg1)))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(lbpg2)
            .addComponent(rbtnmarte)
            .addComponent(rbtnjupiter)
            .addComponent(rbtntierra)
            .addComponent(rbtnsaturno))
          .addComponent(lbr2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(lbpg3)
            .addComponent(rbtnola)
            .addComponent(rbtndesicion)
            .addComponent(rbtnhay)
            .addComponent(rbtnahi))
          .addComponent(lbr3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(lbpg4)
            .addComponent(cboxsagaz)
            .addComponent(cboxlisto)
            .addComponent(cboxlerdo)
            .addComponent(cboxastuto))
          .addComponent(lbr4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(btnmostrar)
        .addContainerGap(21, Short.MAX_VALUE))
    );

    getAccessibleContext().setAccessibleName("Cuestionario");
    getAccessibleContext().setAccessibleDescription("");

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrarActionPerformed
  if (noButtonSelected() && nocheckSelected()){
       JOptionPane.showMessageDialog(null, "No selecciono ninguna opción", "Error", JOptionPane.ERROR_MESSAGE);
       
     } else {
    Validar1Pregunta();
         Validar2Pregunta();
          Validar3Pregunta();
           Validar4Pregunta();
  
  }  
        
      
  }//GEN-LAST:event_btnmostrarActionPerformed

  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnmostrar;
  private javax.swing.JCheckBox cboxastuto;
  private javax.swing.JCheckBox cboxlerdo;
  private javax.swing.JCheckBox cboxlisto;
  private javax.swing.JCheckBox cboxsagaz;
  private javax.swing.JLabel lbpg1;
  private javax.swing.JLabel lbpg2;
  private javax.swing.JLabel lbpg3;
  private javax.swing.JLabel lbpg4;
  private javax.swing.JLabel lbr1;
  private javax.swing.JLabel lbr2;
  private javax.swing.JLabel lbr3;
  private javax.swing.JLabel lbr4;
  private javax.swing.JRadioButton rbtn31;
  private javax.swing.JRadioButton rbtn34;
  private javax.swing.JRadioButton rbtn40;
  private javax.swing.JRadioButton rbtn58;
  private javax.swing.JRadioButton rbtnahi;
  private javax.swing.JRadioButton rbtndesicion;
  private javax.swing.JRadioButton rbtnhay;
  private javax.swing.JRadioButton rbtnjupiter;
  private javax.swing.JRadioButton rbtnmarte;
  private javax.swing.JRadioButton rbtnola;
  private javax.swing.JRadioButton rbtnsaturno;
  private javax.swing.JRadioButton rbtntierra;
  // End of variables declaration//GEN-END:variables
}
