/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package trabajo.acumulativo;

import java.awt.Color;

import javax.swing.JOptionPane;

/**
 *
 * @author yesner
 */
public class FrmDistribuidora extends javax.swing.JInternalFrame {

  String m1, m2 ,m3,m4 ;
  double p=0,desc=0,pago; 
  /**
   * Creates new form FrmDistribuidora
   */
  public FrmDistribuidora() {
    initComponents();
  }
  
  void calcular(){
      
    try {
      m1="Honda";
       m2="Yamaha";
        m3="Suzuki";
         m4="otros";
       p = Integer.parseInt(txtpre.getText());
 String modelo = txtmar.getText();
 
      if (txtmar.getText().equalsIgnoreCase("") || txtpre.getText().equalsIgnoreCase("") || txtdes.getText().equalsIgnoreCase("")){
          JOptionPane.showMessageDialog(null, "Ingrese bien los datos");
      }else {
         if(m1.equalsIgnoreCase(modelo)){
        desc = p * 0.05;
        pago = p - desc;
           lbdes.setText("El descuento es : "+sincero(desc));
           lbdes.setForeground(Color.BLUE);
           lbcosto.setText("El costo de la moto es : " + sincero(pago));

        } else if(m2.equalsIgnoreCase(modelo)){
                   desc = p * 0.08;
                   pago = p - desc;
                      lbdes.setText("El descuento es : "+sincero(desc));
                      lbdes.setForeground(Color.BLUE);
                      lbcosto.setText("El costo de la moto es : " + sincero(pago)); 
          }else if(m3.equalsIgnoreCase(modelo)) {
                    desc = p * 0.10;
                    pago = p - desc;
                       lbdes.setText("El descuento es : "+sincero(desc));
                       lbdes.setForeground(Color.BLUE);
                       lbcosto.setText("El costo de la moto es : " +sincero(pago)); 
            }else if(m4.equalsIgnoreCase(modelo)){
                      desc = p * 0.02;
                      pago = p - desc;
                         lbdes.setText("El descuento es : "+sincero(desc));
                         lbdes.setForeground(Color.BLUE);
                         lbcosto.setText("El costo de la moto es : " + sincero(pago));
             }
      
      }
      
    } catch (Exception e) {
      JOptionPane.showMessageDialog(null, e.getMessage());
    }
 
    
  }
  
  public String sincero(double resultado){
      String retorno="";
      retorno=Double.toString(resultado);
      
      if(resultado%1==0){
        retorno=retorno.substring(0, retorno.length()-2);
      }
    return retorno;
    }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    txtpre = new javax.swing.JTextField();
    txtmar = new javax.swing.JTextField();
    txtdes = new javax.swing.JTextField();
    btncalcular = new javax.swing.JButton();
    lbdes = new javax.swing.JLabel();
    lbcosto = new javax.swing.JLabel();

    txtpre.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese el precio de la moto"));

    txtmar.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese la marca de la moto"));

    txtdes.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese el descuento de la moto"));

    btncalcular.setText("Calcular");
    btncalcular.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btncalcularActionPerformed(evt);
      }
    });

    lbdes.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N

    lbcosto.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(txtmar, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtpre, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(txtdes, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(150, 150, 150)
            .addComponent(btncalcular))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(110, 110, 110)
            .addComponent(lbdes, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(126, 126, 126)
            .addComponent(lbcosto, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(76, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(29, 29, 29)
        .addComponent(txtpre, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(txtmar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(txtdes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(btncalcular)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(lbdes, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(lbcosto, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(47, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btncalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularActionPerformed
    if(txtpre.getText().equalsIgnoreCase("") && txtmar.getText().equalsIgnoreCase("") && txtdes.getText().equalsIgnoreCase("")){
        JOptionPane.showMessageDialog(null, "Debe ingresar los datos", "Error", JOptionPane.ERROR_MESSAGE);
    }else{
      calcular();
    }
    
    
  }//GEN-LAST:event_btncalcularActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btncalcular;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JLabel lbcosto;
  private javax.swing.JLabel lbdes;
  private javax.swing.JTextField txtdes;
  private javax.swing.JTextField txtmar;
  private javax.swing.JTextField txtpre;
  // End of variables declaration//GEN-END:variables
}
