/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package trabajo.acumulativo;

import javax.swing.JOptionPane;

/**
 *
 * @author yesner
 */
public class FrmIva extends javax.swing.JInternalFrame {

        double valorVenta ;
        double descuento = 0;
        double iva = 0;
        double precioTotal = 0;
  /**
   * Creates new form FrmIva
   */
  public FrmIva() {
    initComponents();
  }
  
  void calculo(){
    
    try {
      
      if (txtpreciov.getText().equalsIgnoreCase("")){
      JOptionPane.showMessageDialog(null, "Ingrese el precio de venta", "Error", JOptionPane.ERROR_MESSAGE);
      
      }else {
         valorVenta = Double.parseDouble(txtpreciov.getText());
             if (valorVenta < 100) {
                   descuento = valorVenta * 0.10;
                } else if (valorVenta < 500 && valorVenta > 100) {
                   descuento = valorVenta * 0.10;
                } else if (valorVenta > 500){
                   descuento = valorVenta * 0.15;
               }
        iva = (valorVenta - descuento) * 0.18;
        precioTotal = valorVenta - descuento + iva;
     
        lbvalordventa.setText(sincero(valorVenta));
        lbdes.setText(sincero(descuento));
        lbiva.setText(sincero(iva));
        lbpreciot.setText(sincero(precioTotal));
       
      
      }
      
    } catch (Exception e) {
      JOptionPane.showMessageDialog(null, e.getMessage());
    }
     
  
  }
  
   public String sincero(double resultado){
      String retorno="";
      retorno=Double.toString(resultado);
      
      if(resultado%1==0){
        retorno=retorno.substring(0, retorno.length()-2);
      }
    return retorno;
    }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    txtpreciov = new javax.swing.JTextField();
    btncalcular = new javax.swing.JButton();
    lbvalordventa = new javax.swing.JLabel();
    lbdes = new javax.swing.JLabel();
    lbiva = new javax.swing.JLabel();
    lbpreciot = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();

    jPanel1.setBackground(new java.awt.Color(204, 255, 255));

    txtpreciov.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese el valor de la venta"));

    btncalcular.setText("Calcular");
    btncalcular.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btncalcularActionPerformed(evt);
      }
    });

    jLabel1.setText("Valor de la venta");

    jLabel2.setText("Descuento");

    jLabel3.setText("IVA");

    jLabel4.setText("Precio Total");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel2)
              .addComponent(jLabel3)
              .addComponent(jLabel4))
            .addGap(131, 131, 131)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(lbpreciot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(lbiva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
              .addComponent(lbdes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbvalordventa, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(33, 33, 33))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(55, 55, 55)
            .addComponent(txtpreciov, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(106, 106, 106)
            .addComponent(btncalcular)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(33, 33, 33)
        .addComponent(txtpreciov, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(btncalcular)
        .addGap(39, 39, 39)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addComponent(lbvalordventa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(lbdes, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(jLabel2))
            .addGap(18, 18, 18)
            .addComponent(lbiva, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(jLabel3))
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(lbpreciot, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel4))
        .addContainerGap(26, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btncalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularActionPerformed
   calculo();
  }//GEN-LAST:event_btncalcularActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btncalcular;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JLabel lbdes;
  private javax.swing.JLabel lbiva;
  private javax.swing.JLabel lbpreciot;
  private javax.swing.JLabel lbvalordventa;
  private javax.swing.JTextField txtpreciov;
  // End of variables declaration//GEN-END:variables
}
