/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package trabajo.acumulativo;

import java.awt.HeadlessException;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
/**
 *
 * @author yesner
 */
public class FrmMiniEncuesta extends javax.swing.JInternalFrame {

  private String informacion1 = "";
  private String informacion2 = "";
  
  /**
   * Creates new form FrmMiniEncuesta
   */
  public FrmMiniEncuesta() {
    initComponents();
    Quitarselection();
  }
  
  void Quitarselection(){
       ButtonGroup btg = new ButtonGroup();
    
       btg.add(rbtnwindows);
       btg.add(rbtnlinux);
       btg.add(rbtnmac);
  
  }
  
  public void validar(){
    
    try {
          if (rbtnwindows.isSelected() || rbtnlinux.isSelected() || rbtnmac.isSelected()) {
                   JRadioButton[] rbt = {rbtnwindows,rbtnlinux,rbtnmac};
                        for (JRadioButton rbt1 : rbt) {
                               if (rbt1.isSelected()) {
                                       informacion1 = rbt1.getText();
                                 }
                           }
            
                     JCheckBox[] cbt = {cbtnprogramacion,cbtndiseño,cbtnadmi};
                      
                      
                        for (JCheckBox cbt1 : cbt) {
                             if (cbt1.isSelected()) {
                                     informacion2 += cbt1.getText() + ",";
                               }
                           }
                 String informacion3 = "y el numero de horas dedicadas al ordenador son:"+jSlidervalor.getValue();
          JOptionPane.showMessageDialog(null, "Tu sistema preferido es:" +informacion1 +"\n" +"Tus especialidades son:" +informacion2+"\n"+informacion3, "Muestra de Datos", JOptionPane.ERROR_MESSAGE, new ImageIcon("/Users/yesner/Repositorio/Trabajo acumulativo/src/Icon/icons8-base-de-datos-80.png"));
       
    }else {
            JOptionPane.showMessageDialog(null, "Seleccione un sistema operativo");
          }
              
          
     } catch (HeadlessException e) {
       JOptionPane.showConfirmDialog(null, e.getMessage());
    }
       
  }
  
 
  

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    rbtnwindows = new javax.swing.JRadioButton();
    rbtnlinux = new javax.swing.JRadioButton();
    rbtnmac = new javax.swing.JRadioButton();
    jSeparator1 = new javax.swing.JSeparator();
    jLabel2 = new javax.swing.JLabel();
    cbtnprogramacion = new javax.swing.JCheckBox();
    cbtndiseño = new javax.swing.JCheckBox();
    cbtnadmi = new javax.swing.JCheckBox();
    jSeparator2 = new javax.swing.JSeparator();
    jLabel3 = new javax.swing.JLabel();
    jSlidervalor = new javax.swing.JSlider();
    lbvalorslider = new javax.swing.JLabel();
    btngenerar = new javax.swing.JButton();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();

    jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
    jLabel1.setText("Elige un sistema operativo");

    rbtnwindows.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
    rbtnwindows.setText("Windows");
    rbtnwindows.setBorderPainted(true);

    rbtnlinux.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
    rbtnlinux.setText("Linux");
    rbtnlinux.setBorderPainted(true);

    rbtnmac.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
    rbtnmac.setText("Mac");
    rbtnmac.setBorderPainted(true);

    jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
    jLabel2.setText("Elige tu especialidad");

    cbtnprogramacion.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
    cbtnprogramacion.setText("Programación");
    cbtnprogramacion.setBorderPaintedFlat(true);

    cbtndiseño.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
    cbtndiseño.setText("Diseño Gráfico");
    cbtndiseño.setBorderPaintedFlat(true);

    cbtnadmi.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
    cbtnadmi.setText("Administración");
    cbtnadmi.setBorderPaintedFlat(true);

    jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
    jLabel3.setText("Horas que dedicas en el ordenador");

    jSlidervalor.setMajorTickSpacing(1);
    jSlidervalor.setMaximum(10);
    jSlidervalor.setPaintTicks(true);
    jSlidervalor.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        jSlidervalorStateChanged(evt);
      }
    });

    lbvalorslider.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
    lbvalorslider.setText("0");

    btngenerar.setText("Generar");
    btngenerar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btngenerarActionPerformed(evt);
      }
    });

    jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-windows8-40.png"))); // NOI18N

    jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-linux-48.png"))); // NOI18N

    jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-logo-de-mac-40.png"))); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jSeparator1)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 47, Short.MAX_VALUE)
                .addComponent(lbvalorslider, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jSlidervalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGroup(layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(btngenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addComponent(jLabel5)
                  .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(rbtnlinux)
                  .addComponent(rbtnmac)))
              .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(cbtnadmi)
                  .addComponent(cbtndiseño)
                  .addComponent(cbtnprogramacion)
                  .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
              .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnwindows))
              .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)))
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(jLabel3)
        .addGap(26, 26, 26))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jLabel1)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(7, 7, 7)
            .addComponent(jLabel4))
          .addGroup(layout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(rbtnwindows)))
        .addGap(6, 6, 6)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addGap(9, 9, 9)
            .addComponent(rbtnlinux)))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel6)
          .addComponent(rbtnmac))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel2)
        .addGap(18, 18, 18)
        .addComponent(cbtnprogramacion)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cbtndiseño)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cbtnadmi)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel3)
        .addGap(34, 34, 34)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jSlidervalor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(lbvalorslider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(18, 18, 18)
        .addComponent(btngenerar)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btngenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenerarActionPerformed
    validar();
    
  }//GEN-LAST:event_btngenerarActionPerformed

  private void jSlidervalorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlidervalorStateChanged
    lbvalorslider.setText(String.valueOf(jSlidervalor.getValue()));
  }//GEN-LAST:event_jSlidervalorStateChanged


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btngenerar;
  private javax.swing.JCheckBox cbtnadmi;
  private javax.swing.JCheckBox cbtndiseño;
  private javax.swing.JCheckBox cbtnprogramacion;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JSeparator jSeparator2;
  private javax.swing.JSlider jSlidervalor;
  private javax.swing.JLabel lbvalorslider;
  private javax.swing.JRadioButton rbtnlinux;
  private javax.swing.JRadioButton rbtnmac;
  private javax.swing.JRadioButton rbtnwindows;
  // End of variables declaration//GEN-END:variables
}
