/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package trabajo.acumulativo;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author yesner
 */
public class FrmNotas extends javax.swing.JInternalFrame {

  double nota1, nota2 ,nota3,nota4, promedio;
  /**
   * Creates new form FrmNotas
   */
  public FrmNotas() {
    initComponents();
  }
  
  
  
  void calcular(){
    nota1= Double.parseDouble(txtn1.getText());
     nota2= Double.parseDouble(txtn2.getText());
      nota3= Double.parseDouble(txtn3.getText());
       nota4= Double.parseDouble(txtn4.getText());
  
       promedio = (nota1+nota2+nota3+nota4)/4;
       
       
          if(promedio >= 13){
                lbresult.setText(promedio+" "+" APROBADO ");
                  lbresult.setForeground(Color.BLUE);
               lbaviso.setText(" Certificado en MS-OFFICE ");
          } else {
                lbresult.setText(promedio+" "+" DESAPROBADO ");
                  lbresult.setForeground(Color.red);
               lbaviso.setText(" ");
          }
     
           
}
  
  
  

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel5 = new javax.swing.JPanel();
    txtn1 = new javax.swing.JTextField();
    txtn2 = new javax.swing.JTextField();
    txtn3 = new javax.swing.JTextField();
    txtn4 = new javax.swing.JTextField();
    btnpromedio = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    lbresult = new javax.swing.JLabel();
    lbaviso = new javax.swing.JLabel();

    jPanel5.setBackground(new java.awt.Color(204, 204, 255));

    txtn1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese la primer nota"));

    txtn2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese la seginda nota"));

    txtn3.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese la tercer nota"));

    txtn4.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese la cuarta nota"));

    btnpromedio.setText("Promediar");
    btnpromedio.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnpromedioActionPerformed(evt);
      }
    });

    jLabel1.setText("Condicion:");

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel5Layout.createSequentialGroup()
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbresult, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel5Layout.createSequentialGroup()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                  .addComponent(txtn1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                  .addComponent(txtn2, javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(txtn3, javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(txtn4, javax.swing.GroupLayout.Alignment.LEADING)))
              .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btnpromedio))
              .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lbaviso, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(0, 72, Short.MAX_VALUE)))
        .addContainerGap())
    );
    jPanel5Layout.setVerticalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel5Layout.createSequentialGroup()
        .addGap(13, 13, 13)
        .addComponent(txtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(txtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(txtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(txtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(9, 9, 9)
        .addComponent(btnpromedio)
        .addGap(18, 18, 18)
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lbresult, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel1))
        .addGap(32, 32, 32)
        .addComponent(lbaviso, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(27, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnpromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpromedioActionPerformed
    if (txtn1.getText().equalsIgnoreCase("") && txtn2.getText().equalsIgnoreCase("") && txtn3.getText().equalsIgnoreCase("") && txtn4.getText().equalsIgnoreCase("")) {
         JOptionPane.showMessageDialog(null, "Rellenar los datos", "Error", JOptionPane.ERROR_MESSAGE);
        }else if (txtn1.getText().equalsIgnoreCase("") || txtn2.getText().equalsIgnoreCase("") || txtn3.getText().equalsIgnoreCase("") || txtn4.getText().equalsIgnoreCase("")){
        JOptionPane.showMessageDialog(null, "Rellene bien los datos", "Error", JOptionPane.ERROR_MESSAGE);
    }else{
        calcular();
        }
    
    
  }//GEN-LAST:event_btnpromedioActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnpromedio;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JLabel lbaviso;
  private javax.swing.JLabel lbresult;
  private javax.swing.JTextField txtn1;
  private javax.swing.JTextField txtn2;
  private javax.swing.JTextField txtn3;
  private javax.swing.JTextField txtn4;
  // End of variables declaration//GEN-END:variables
}
