/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package trabajo.acumulativo;

/**
 *
 * @author yesner
 */
public class MDIPrincipal extends javax.swing.JFrame {

  /**
   * Creates new form MDIPrincipal
   */
  public MDIPrincipal() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    desktopPane = new javax.swing.JDesktopPane();
    menuBar = new javax.swing.JMenuBar();
    fileMenu = new javax.swing.JMenu();
    openMenuItem = new javax.swing.JMenuItem();
    saveMenuItem = new javax.swing.JMenuItem();
    saveAsMenuItem = new javax.swing.JMenuItem();
    exitMenuItem = new javax.swing.JMenuItem();
    editMenu = new javax.swing.JMenu();
    MenuEncuesta = new javax.swing.JMenuItem();
    MenuEvaluar = new javax.swing.JMenuItem();
    MenuCuestionario = new javax.swing.JMenuItem();
    MenuDistribuidora = new javax.swing.JMenuItem();
    MenuNotas = new javax.swing.JMenuItem();
    MenuIva = new javax.swing.JMenuItem();
    helpMenu = new javax.swing.JMenu();
    contentMenuItem = new javax.swing.JMenuItem();
    aboutMenuItem = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    desktopPane.setLayout(null);

    fileMenu.setMnemonic('f');
    fileMenu.setText("File");

    openMenuItem.setMnemonic('o');
    openMenuItem.setText("Open");
    fileMenu.add(openMenuItem);

    saveMenuItem.setMnemonic('s');
    saveMenuItem.setText("Save");
    fileMenu.add(saveMenuItem);

    saveAsMenuItem.setMnemonic('a');
    saveAsMenuItem.setText("Save As ...");
    saveAsMenuItem.setDisplayedMnemonicIndex(5);
    fileMenu.add(saveAsMenuItem);

    exitMenuItem.setMnemonic('x');
    exitMenuItem.setText("Exit");
    exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        exitMenuItemActionPerformed(evt);
      }
    });
    fileMenu.add(exitMenuItem);

    menuBar.add(fileMenu);

    editMenu.setMnemonic('e');
    editMenu.setText("Trabajos");

    MenuEncuesta.setMnemonic('t');
    MenuEncuesta.setText("MiniEncuesta");
    MenuEncuesta.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        MenuEncuestaActionPerformed(evt);
      }
    });
    editMenu.add(MenuEncuesta);

    MenuEvaluar.setMnemonic('y');
    MenuEvaluar.setText("Evaluar #");
    MenuEvaluar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        MenuEvaluarActionPerformed(evt);
      }
    });
    editMenu.add(MenuEvaluar);

    MenuCuestionario.setMnemonic('p');
    MenuCuestionario.setText("Cuestionario");
    MenuCuestionario.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        MenuCuestionarioActionPerformed(evt);
      }
    });
    editMenu.add(MenuCuestionario);

    MenuDistribuidora.setText("Distribuidora");
    MenuDistribuidora.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        MenuDistribuidoraActionPerformed(evt);
      }
    });
    editMenu.add(MenuDistribuidora);

    MenuNotas.setMnemonic('d');
    MenuNotas.setText("Notas");
    MenuNotas.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        MenuNotasActionPerformed(evt);
      }
    });
    editMenu.add(MenuNotas);

    MenuIva.setText("Iva");
    MenuIva.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        MenuIvaActionPerformed(evt);
      }
    });
    editMenu.add(MenuIva);

    menuBar.add(editMenu);

    helpMenu.setMnemonic('h');
    helpMenu.setText("Help");

    contentMenuItem.setMnemonic('c');
    contentMenuItem.setText("Contents");
    helpMenu.add(contentMenuItem);

    aboutMenuItem.setMnemonic('a');
    aboutMenuItem.setText("About");
    helpMenu.add(aboutMenuItem);

    menuBar.add(helpMenu);

    setJMenuBar(menuBar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
      System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

  private void MenuEncuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEncuestaActionPerformed
    FrmMiniEncuesta M = new FrmMiniEncuesta();
    this.desktopPane.add(M);
    M.setVisible(true);
  }//GEN-LAST:event_MenuEncuestaActionPerformed

  private void MenuEvaluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEvaluarActionPerformed
    FrmEvaluar E = new FrmEvaluar();
    this.desktopPane.add(E);
    E.setVisible(true);
  }//GEN-LAST:event_MenuEvaluarActionPerformed

  private void MenuCuestionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCuestionarioActionPerformed
    FrmCuestionario C = new FrmCuestionario();
    this.desktopPane.add(C);
    C.setVisible(true);
  }//GEN-LAST:event_MenuCuestionarioActionPerformed

  private void MenuNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuNotasActionPerformed
    FrmNotas N = new FrmNotas();
    this.desktopPane.add(N);
    N.setVisible(true);
  }//GEN-LAST:event_MenuNotasActionPerformed

  private void MenuDistribuidoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDistribuidoraActionPerformed
    FrmDistribuidora D = new FrmDistribuidora();
    this.desktopPane.add(D);
    D.setVisible(true);
  }//GEN-LAST:event_MenuDistribuidoraActionPerformed

  private void MenuIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuIvaActionPerformed
    FrmIva I = new FrmIva();
    this.desktopPane.add(I);
    I.setVisible(true);
  }//GEN-LAST:event_MenuIvaActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MDIPrincipal().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuItem MenuCuestionario;
  private javax.swing.JMenuItem MenuDistribuidora;
  private javax.swing.JMenuItem MenuEncuesta;
  private javax.swing.JMenuItem MenuEvaluar;
  private javax.swing.JMenuItem MenuIva;
  private javax.swing.JMenuItem MenuNotas;
  private javax.swing.JMenuItem aboutMenuItem;
  private javax.swing.JMenuItem contentMenuItem;
  private javax.swing.JDesktopPane desktopPane;
  private javax.swing.JMenu editMenu;
  private javax.swing.JMenuItem exitMenuItem;
  private javax.swing.JMenu fileMenu;
  private javax.swing.JMenu helpMenu;
  private javax.swing.JMenuBar menuBar;
  private javax.swing.JMenuItem openMenuItem;
  private javax.swing.JMenuItem saveAsMenuItem;
  private javax.swing.JMenuItem saveMenuItem;
  // End of variables declaration//GEN-END:variables

}
